# Generated by Django 2.2.28 on 2026-02-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZomatoDB',
            fields=[
                ('orderNo', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('dish', models.CharField(max_length=20)),
                ('rating', models.FloatField()),
                ('address', models.TextField()),
                ('Mobile_no', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
